source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'IOSLazyImage_Example', :exclusive => true do
  pod 'IOSLazyImage', :path => '../'
end

target 'IOSLazyImage_Tests', :exclusive => true do
  pod 'IOSLazyImage', :path => '../'

  
end
